-- ============================================================================
-- 0023_seed_spell_token_library.sql
-- Create the spell-token library (public.token_assets), one per PNG in
-- public/icons/spells/. NAME + IMAGE only. SRD-spelled names. Idempotent:
-- re-running skips a spell token you already have with the same name.
-- ============================================================================

do $$
declare
  me uuid;
begin
  select id into me from auth.users where email = 'vinces.gerardo@gmail.com';
  if me is null then
    raise exception 'No auth user for that email — edit the OWNER email.';
  end if;

  insert into public.token_assets (owner_id, name, image_url, token_type, size_category, details)
  select me, v.name, v.image_url, 'spell', 'medium',
         jsonb_build_object('kind','spell','spell', jsonb_build_object('name', v.name))
  from (values
    ('Acid Splash', '/icons/spells/cantrips/acid_splash.png'),
    ('Blade Ward', '/icons/spells/cantrips/blade_ward.png'),
    ('Booming Blade', '/icons/spells/cantrips/booming_blade.png'),
    ('Bursting Sinew', '/icons/spells/cantrips/bursting_sinew.png'),
    ('Chill Touch', '/icons/spells/cantrips/chill_touch.png'),
    ('Dancing Lights', '/icons/spells/cantrips/dancing_lights.png'),
    ('Eldritch Blast', '/icons/spells/cantrips/eldritch_blast.png'),
    ('Fire Bolt', '/icons/spells/cantrips/firebolt.png'),
    ('Friends', '/icons/spells/cantrips/friends.png'),
    ('Guidance', '/icons/spells/cantrips/guidance.png'),
    ('Light', '/icons/spells/cantrips/light.png'),
    ('Mage Hand', '/icons/spells/cantrips/mage_hand.png'),
    ('Minor Illusion', '/icons/spells/cantrips/minor_illusion.png'),
    ('Poison Spray', '/icons/spells/cantrips/poison_spray.png'),
    ('Produce Flame', '/icons/spells/cantrips/produce_flame.png'),
    ('Ray of Frost', '/icons/spells/cantrips/ray_of_frost.png'),
    ('Resistance', '/icons/spells/cantrips/resistance.png'),
    ('Sacred Flame', '/icons/spells/cantrips/sacred_flame.png'),
    ('Shillelagh', '/icons/spells/cantrips/shillelagh.png'),
    ('Shocking Grasp', '/icons/spells/cantrips/shocking_grasp.png'),
    ('Thaumaturgy', '/icons/spells/cantrips/thaumaturgy.png'),
    ('Thorn Whip', '/icons/spells/cantrips/thorn_whip.png'),
    ('Toll the Dead', '/icons/spells/cantrips/toll_the_dead.png'),
    ('True Strike', '/icons/spells/cantrips/true_strike.png'),
    ('Vicious Mockery', '/icons/spells/cantrips/vicious_mockery.png'),
    ('Animal Friendship', '/icons/spells/level_1/animal_friendship.png'),
    ('Armor of Agathys', '/icons/spells/level_1/armor_of_agathys.png'),
    ('Arms of Hadar', '/icons/spells/level_1/arms_of_hadar.png'),
    ('Bane', '/icons/spells/level_1/bane.png'),
    ('Bless', '/icons/spells/level_1/bless.png'),
    ('Burning Hands', '/icons/spells/level_1/burning_hands.png'),
    ('Charm Person', '/icons/spells/level_1/charm_person.png'),
    ('Chromatic Orb', '/icons/spells/level_1/chromatic_orb.png'),
    ('Color Spray', '/icons/spells/level_1/color_spray.png'),
    ('Command', '/icons/spells/level_1/command.png'),
    ('Compelled Duel', '/icons/spells/level_1/compelled_duel.png'),
    ('Create or Destroy Water', '/icons/spells/level_1/create_or_destroy_water.png'),
    ('Cure Wounds', '/icons/spells/level_1/cure_wounds.png'),
    ('Disguise Self', '/icons/spells/level_1/disguise_self.png'),
    ('Dissonant Whispers', '/icons/spells/level_1/dissonant_whispers.png'),
    ('Divine Favor', '/icons/spells/level_1/divine_favor.png'),
    ('Enhance Leap', '/icons/spells/level_1/enhance_leap.png'),
    ('Ensnaring Strike', '/icons/spells/level_1/ensnaring_strike.png'),
    ('Entangle', '/icons/spells/level_1/entangle.png'),
    ('Expeditious Retreat', '/icons/spells/level_1/expeditious_retreat.png'),
    ('Faerie Fire', '/icons/spells/level_1/faerie_fire.png'),
    ('False Life', '/icons/spells/level_1/false_life.png'),
    ('Feather Fall', '/icons/spells/level_1/feather_fall.png'),
    ('Find Familiar', '/icons/spells/level_1/find_familiar.png'),
    ('Fog Cloud', '/icons/spells/level_1/fog_cloud.png'),
    ('Goodberry', '/icons/spells/level_1/goodberry.png'),
    ('Grease', '/icons/spells/level_1/grease.png'),
    ('Guiding Bolt', '/icons/spells/level_1/guiding_bolt.png'),
    ('Hail of Thorns', '/icons/spells/level_1/hail_of_thorns.png'),
    ('Healing Word', '/icons/spells/level_1/healing_word.png'),
    ('Hellish Rebuke', '/icons/spells/level_1/hellish_rebuke.png'),
    ('Heroism', '/icons/spells/level_1/heroism.png'),
    ('Hex', '/icons/spells/level_1/hex.png'),
    ('Hunter''s Mark', '/icons/spells/level_1/hunters_mark.png'),
    ('Ice Knife', '/icons/spells/level_1/ice_knife.png'),
    ('Inflict Wounds', '/icons/spells/level_1/inflict_wounds.png'),
    ('Longstrider', '/icons/spells/level_1/longstrider.png'),
    ('Mage Armor', '/icons/spells/level_1/mage_armor.png'),
    ('Magic Missile', '/icons/spells/level_1/magic_missile.png'),
    ('Protection from Evil and Good', '/icons/spells/level_1/protection_from_evil_and_good.png'),
    ('Ray of Sickness', '/icons/spells/level_1/ray_of_sickness.png'),
    ('Sanctuary', '/icons/spells/level_1/sanctuary.png'),
    ('Searing Smite', '/icons/spells/level_1/searing_smite.png'),
    ('Shield', '/icons/spells/level_1/shield.png'),
    ('Sleep', '/icons/spells/level_1/sleep.png'),
    ('Speak with Animals', '/icons/spells/level_1/speak_with_animals.png'),
    ('Tasha''s Hideous Laughter', '/icons/spells/level_1/tashas_hideous_laughter.png'),
    ('Thunderous Smite', '/icons/spells/level_1/thunderous_smite.png'),
    ('Thunderwave', '/icons/spells/level_1/thunderwave.png'),
    ('Witch Bolt', '/icons/spells/level_1/witch_bolt.png'),
    ('Wrathful Smite', '/icons/spells/level_1/wrathful_smite.png'),
    ('Aid', '/icons/spells/level_2/aid.png'),
    ('Arcane Lock', '/icons/spells/level_2/arcane_lock.png'),
    ('Barkskin', '/icons/spells/level_2/barkskin.png'),
    ('Blindness', '/icons/spells/level_2/blindness.png'),
    ('Blur', '/icons/spells/level_2/blur.png'),
    ('Branding Smite', '/icons/spells/level_2/branding_smite.png'),
    ('Calm Emotions', '/icons/spells/level_2/calm_emotions.png'),
    ('Cloud of Daggers', '/icons/spells/level_2/cloud_of_daggers.png'),
    ('Crown of Madness', '/icons/spells/level_2/crown_of_madness.png'),
    ('Darkness', '/icons/spells/level_2/darkness.png'),
    ('Darkvision', '/icons/spells/level_2/darkvision.png'),
    ('Detect Thoughts', '/icons/spells/level_2/detect_thoughts.png'),
    ('Enhance Ability', '/icons/spells/level_2/enhance_ability.png'),
    ('Enlarge/Reduce', '/icons/spells/level_2/enlarge_reduce.png'),
    ('Enthrall', '/icons/spells/level_2/enthrall.png'),
    ('Flame Blade', '/icons/spells/level_2/flame_blade.png'),
    ('Flaming Sphere', '/icons/spells/level_2/flaming_sphere.png'),
    ('Gust of Wind', '/icons/spells/level_2/gust_of_wind.png'),
    ('Heat Metal', '/icons/spells/level_2/heat_metal.png'),
    ('Hold Person', '/icons/spells/level_2/hold_person.png'),
    ('Invisibility', '/icons/spells/level_2/invisibility.png'),
    ('Knock', '/icons/spells/level_2/knock.png'),
    ('Lesser Restoration', '/icons/spells/level_2/lesser_restoration.png'),
    ('Magic Weapon', '/icons/spells/level_2/magic_weapon.png'),
    ('Melf''s Acid Arrow', '/icons/spells/level_2/melfs_acid_arrow.png'),
    ('Mirror Image', '/icons/spells/level_2/mirror_image.png'),
    ('Misty Step', '/icons/spells/level_2/misty_step.png'),
    ('Moonbeam', '/icons/spells/level_2/moonbeam.png'),
    ('Pass Without Trace', '/icons/spells/level_2/pass_without_trace.png'),
    ('Phantasmal Force', '/icons/spells/level_2/phantasmal_force.png'),
    ('Prayer of Healing', '/icons/spells/level_2/prayer_of_healing.png'),
    ('Protection from Poison', '/icons/spells/level_2/protection_from_poison.png'),
    ('Ray of Enfeeblement', '/icons/spells/level_2/ray_of_enfeeblement.png'),
    ('Scorching Ray', '/icons/spells/level_2/scorching_ray.png'),
    ('See Invisibility', '/icons/spells/level_2/see_invisibility.png'),
    ('Shadow Blade', '/icons/spells/level_2/shadow_blade.png'),
    ('Shatter', '/icons/spells/level_2/shatter.png'),
    ('Silence', '/icons/spells/level_2/silence.png'),
    ('Spike Growth', '/icons/spells/level_2/spike_growth.png'),
    ('Spiritual Weapon', '/icons/spells/level_2/spiritual_weapon.png'),
    ('Warding Bond', '/icons/spells/level_2/warding_bond.png'),
    ('Web', '/icons/spells/level_2/web.png'),
    ('Animate Dead', '/icons/spells/level_3/animate_dead.png'),
    ('Beacon of Hope', '/icons/spells/level_3/beacon_of_hope.png'),
    ('Bestow Curse', '/icons/spells/level_3/bestow_curse.png'),
    ('Blinding Smite', '/icons/spells/level_3/blinding_smite.png'),
    ('Blink', '/icons/spells/level_3/blink.png'),
    ('Call Lightning', '/icons/spells/level_3/call_lightning.png'),
    ('Conjure Barrage', '/icons/spells/level_3/conjure_barrage.png'),
    ('Counterspell', '/icons/spells/level_3/counterspell.png'),
    ('Crusader''s Mantle', '/icons/spells/level_3/crusaders_mantle.png'),
    ('Daylight', '/icons/spells/level_3/daylight.png'),
    ('Elemental Weapon', '/icons/spells/level_3/elemental_weapon.png'),
    ('Fear', '/icons/spells/level_3/fear.png'),
    ('Feign Death', '/icons/spells/level_3/feign_death.png'),
    ('Fireball', '/icons/spells/level_3/fireball.png'),
    ('Gaseous Form', '/icons/spells/level_3/gaseous_form.png'),
    ('Glyph of Warding', '/icons/spells/level_3/glyph_of_warding.png'),
    ('Grant Flight', '/icons/spells/level_3/grant_flight.png'),
    ('Haste', '/icons/spells/level_3/haste.png'),
    ('Hunger of Hadar', '/icons/spells/level_3/hunger_of_hadar.png'),
    ('Hypnotic Pattern', '/icons/spells/level_3/hypnotic_pattern.png'),
    ('Lightning Arrow', '/icons/spells/level_3/lightning_arrow.png'),
    ('Lightning Bolt', '/icons/spells/level_3/lightning_bolt.png'),
    ('Mass Healing Word', '/icons/spells/level_3/mass_healing_word.png'),
    ('Plant Growth', '/icons/spells/level_3/plant_growth.png'),
    ('Protection from Energy', '/icons/spells/level_3/protection_from_energy.png'),
    ('Remove Curse', '/icons/spells/level_3/remove_curse.png'),
    ('Revivify', '/icons/spells/level_3/revivify.png'),
    ('Sleet Storm', '/icons/spells/level_3/sleet_storm.png'),
    ('Slow', '/icons/spells/level_3/slow.png'),
    ('Speak with Dead', '/icons/spells/level_3/speak_with_dead.png'),
    ('Spirit Guardians', '/icons/spells/level_3/spirit_guardians.png'),
    ('Stinking Cloud', '/icons/spells/level_3/stinking_cloud.png'),
    ('Vampiric Touch', '/icons/spells/level_3/vampiric_touch.png'),
    ('Warden of Vitality', '/icons/spells/level_3/warden_of_vitality.png'),
    ('Banishment', '/icons/spells/level_4/banishment.png'),
    ('Blight', '/icons/spells/level_4/blight.png'),
    ('Confusion', '/icons/spells/level_4/confusion.png'),
    ('Conjure Minor Elemental', '/icons/spells/level_4/conjure_minor_elemental.png'),
    ('Conjure Woodland Being', '/icons/spells/level_4/conjure_woodland_being.png'),
    ('Death Ward', '/icons/spells/level_4/death_ward.png'),
    ('Dimension Door', '/icons/spells/level_4/dimension_door.png'),
    ('Dominate Beast', '/icons/spells/level_4/dominate_beast.png'),
    ('Evard''s Black Tentacles', '/icons/spells/level_4/evards_black_tentacles.png'),
    ('Fire Shield', '/icons/spells/level_4/fire_shield.png'),
    ('Freedom of Movement', '/icons/spells/level_4/freedom_of_movement.png'),
    ('Grasping Vine', '/icons/spells/level_4/grasping_vine.png'),
    ('Greater Invisibility', '/icons/spells/level_4/greater_invisibility.png'),
    ('Guardian of Faith', '/icons/spells/level_4/guardian_of_faith.png'),
    ('Ice Storm', '/icons/spells/level_4/ice_storm.png'),
    ('Otiluke''s Resilient Sphere', '/icons/spells/level_4/otilukes_resilient_sphere.png'),
    ('Phantasmal Killer', '/icons/spells/level_4/phantasmal_killer.png'),
    ('Polymorph', '/icons/spells/level_4/polymorph.png'),
    ('Staggering Smite', '/icons/spells/level_4/staggering_smite.png'),
    ('Stoneskin', '/icons/spells/level_4/stoneskin.png'),
    ('Wall of Fire', '/icons/spells/level_4/wall_of_fire.png'),
    ('Banishing Smite', '/icons/spells/level_5/banishing_smite.png'),
    ('Cloudkill', '/icons/spells/level_5/cloudkill.png'),
    ('Cone of Cold', '/icons/spells/level_5/cone_of_cold.png'),
    ('Conjure Elemental', '/icons/spells/level_5/conjure_elemental.png'),
    ('Contagion', '/icons/spells/level_5/contagion.png'),
    ('Curriculum of Strategy Artistry of War', '/icons/spells/level_5/curriculum_of_strategy_artistry_of_war.png'),
    ('Destructive Wave', '/icons/spells/level_5/destructive_wave.png'),
    ('Dethrone', '/icons/spells/level_5/dethrone.png'),
    ('Dispel Evil and Good', '/icons/spells/level_5/dispel_evil_and_good.png'),
    ('Dominate Person', '/icons/spells/level_5/dominate_person.png'),
    ('Flame Strike', '/icons/spells/level_5/flame_strike.png'),
    ('Greater Restoration', '/icons/spells/level_5/greater_restoration.png'),
    ('Hold Monster', '/icons/spells/level_5/hold_monster.png'),
    ('Insect Plague', '/icons/spells/level_5/insect_plague.png'),
    ('Mass Cure Wounds', '/icons/spells/level_5/mass_cure_wounds.png'),
    ('Planar Binding', '/icons/spells/level_5/planar_binding.png'),
    ('Seeming', '/icons/spells/level_5/seeming.png'),
    ('Telekinesis', '/icons/spells/level_5/telekinesis.png'),
    ('Wall of Stone', '/icons/spells/level_5/wall_of_stone.png'),
    ('Arcane Gate', '/icons/spells/level_6/arcane_gate.png'),
    ('Blade Barrier', '/icons/spells/level_6/blade_barrier.png'),
    ('Chain Lightning', '/icons/spells/level_6/chain_lightning.png'),
    ('Circle of Death', '/icons/spells/level_6/circle_of_death.png'),
    ('Create Undead', '/icons/spells/level_6/create_undead.png'),
    ('Disintegrate', '/icons/spells/level_6/disintegrate.png'),
    ('Eyebite', '/icons/spells/level_6/eyebite.png'),
    ('Flesh to Stone', '/icons/spells/level_6/flesh_to_stone.png'),
    ('Globe of Invulnerability', '/icons/spells/level_6/globe_of_invulnerability.png'),
    ('Harm', '/icons/spells/level_6/harm.png'),
    ('Heal', '/icons/spells/level_6/heal.png'),
    ('Heroes'' Feast', '/icons/spells/level_6/heroes_feast.png'),
    ('Otiluke''s Freezing Sphere', '/icons/spells/level_6/otilukes_freezing_sphere.png'),
    ('Otto''s Irresistible Dance', '/icons/spells/level_6/ottos_irresistible_dance.png'),
    ('Planar Ally', '/icons/spells/level_6/planar_ally.png'),
    ('Sights of the Seelie Summon Deva', '/icons/spells/level_6/sights_of_the_seelie_summon_deva.png'),
    ('Sunbeam', '/icons/spells/level_6/sunbeam.png'),
    ('Wall of Ice', '/icons/spells/level_6/wall_of_ice.png'),
    ('Wall of Thorns', '/icons/spells/level_6/wall_of_thorns.png'),
    ('Wind Walk', '/icons/spells/level_6/wind_walk.png'),
    ('Formsculpt Tressym', '/icons/spells/level_9/formsculpt_tressym.png'),
    ('Power Word Kill', '/icons/spells/level_9/power_word_kill.png'),
    ('Power Word Ruin', '/icons/spells/level_9/power_word_ruin.png')
  ) as v(name, image_url)
  where not exists (
    select 1 from public.token_assets t
    where t.owner_id = me and t.token_type = 'spell' and t.name = v.name
  );
end $$;
