-- ============================================================================
-- 0026_spell_tokens_full_srd.sql
--
-- Bring the spell-token library to the FULL 339 SRD list.
--   1. Reconcile 3 naming mismatches to their SRD names.
--   2. Insert every SRD spell that has no art yet, with a first-letter
--      monogram placeholder (/icons/spells/_mono/<L>.svg) + full stats.
-- Existing art tokens are untouched. Paste into Supabase SQL Editor -> Run.
-- Idempotent.
-- ============================================================================

do $$
declare
  me uuid;
begin
  select id into me from auth.users where email = 'vinces.gerardo@gmail.com';
  if me is null then raise exception 'No auth user for that email.'; end if;

  -- 1. Reconcile naming mismatches (keep their art).
  update public.token_assets set
    name = 'Blindness/Deafness', details = jsonb_set(coalesce(details,'{}'::jsonb),'{spell,name}', '"Blindness/Deafness"'::jsonb)
    where owner_id = me and token_type = 'spell' and name = 'Blindness';
  update public.token_assets set
    name = 'Conjure Minor Elementals', details = jsonb_set(coalesce(details,'{}'::jsonb),'{spell,name}', '"Conjure Minor Elementals"'::jsonb)
    where owner_id = me and token_type = 'spell' and name = 'Conjure Minor Elemental';
  update public.token_assets set
    name = 'Conjure Woodland Beings', details = jsonb_set(coalesce(details,'{}'::jsonb),'{spell,name}', '"Conjure Woodland Beings"'::jsonb)
    where owner_id = me and token_type = 'spell' and name = 'Conjure Woodland Being';

  -- 2. Insert SRD spells that have no art (placeholder tile + stats).
  insert into public.token_assets (owner_id, name, image_url, token_type, size_category, details)
  select me, v.name, v.image_url, 'spell', 'medium',
         jsonb_build_object('kind','spell','spell', v.spell::jsonb)
  from (values
    ('Druidcraft', '/icons/spells/_mono/D.svg', '{"name":"Druidcraft","level":0,"school":"Transmutation","castingTime":"Action","range":"30 feet","components":"V, S","duration":"Instantaneous","classes":["Druid"]}'),
    ('Elementalism', '/icons/spells/_mono/E.svg', '{"name":"Elementalism","level":0,"school":"Transmutation","castingTime":"Action","range":"30 feet (5 ft. Square)","components":"V, S","duration":"Instantaneous","classes":["Druid","Sorcerer","Wizard"]}'),
    ('Mending', '/icons/spells/_mono/M.svg', '{"name":"Mending","level":0,"school":"Transmutation","castingTime":"1 minute","range":"Touch","components":"V, S, M (two lodestones)","duration":"Instantaneous","classes":["Bard","Cleric","Druid","Sorcerer","Wizard"]}'),
    ('Message', '/icons/spells/_mono/M.svg', '{"name":"Message","level":0,"school":"Transmutation","castingTime":"Action","range":"120 feet","components":"S, M (a copper wire)","duration":"1 round","classes":["Bard","Druid","Sorcerer","Wizard"]}'),
    ('Mind Spike', '/icons/spells/_mono/M.svg', '{"name":"Mind Spike","level":0,"school":"Evocation","castingTime":"Action","range":"120 feet","components":"S","duration":"1 Hour","classes":["Sorcerer","Warlock","Wizard"],"damageType":"psychic"}'),
    ('Prestidigitation', '/icons/spells/_mono/P.svg', '{"name":"Prestidigitation","level":0,"school":"Transmutation","castingTime":"Action","range":"10 feet","components":"V, S","duration":"Up to 1 hour","classes":["Bard","Sorcerer","Warlock","Wizard"]}'),
    ('Sorcerous Burst', '/icons/spells/_mono/S.svg', '{"name":"Sorcerous Burst","level":0,"school":"Evocation","castingTime":"Action","range":"120 feet","components":"V, S","duration":"Instantaneous","classes":["Sorcerer"],"damageType":"varies","areaShape":"sphere","areaSize":5}'),
    ('Spare the Dying', '/icons/spells/_mono/S.svg', '{"name":"Spare the Dying","level":0,"school":"Necromancy","castingTime":"Action","range":"15 feet","components":"V, S","duration":"Instantaneous","classes":["Cleric","Druid"]}'),
    ('Starry Wisp', '/icons/spells/_mono/S.svg', '{"name":"Starry Wisp","level":0,"school":"Evocation","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Instantaneous","classes":["Bard","Druid"],"damageType":"radiant"}'),
    ('Alarm', '/icons/spells/_mono/A.svg', '{"name":"Alarm","level":1,"school":"Abjuration","castingTime":"1 minute or Ritual","range":"30 feet","components":"V, S, M (a bell and silver wire)","duration":"8 hours","classes":["Ranger","Wizard"]}'),
    ('Comprehend Languages', '/icons/spells/_mono/C.svg', '{"name":"Comprehend Languages","level":1,"school":"Divination","castingTime":"Action or Ritual","range":"Self","components":"V, S, M (a pinch of soot and salt)","duration":"1 hour","classes":["Bard","Sorcerer","Warlock","Wizard"]}'),
    ('Detect Evil and Good', '/icons/spells/_mono/D.svg', '{"name":"Detect Evil and Good","level":1,"school":"Divination","castingTime":"Action","range":"Self","components":"V, S","duration":"Concentration, up to 10 minutes","classes":["Cleric","Paladin"],"concentration":true}'),
    ('Detect Magic', '/icons/spells/_mono/D.svg', '{"name":"Detect Magic","level":1,"school":"Divination","castingTime":"Action or Ritual","range":"Self","components":"V, S","duration":"Concentration, up to 10 minutes","classes":["Bard","Cleric","Druid","Paladin","Ranger","Sorcerer","Warlock","Wizard"],"concentration":true}'),
    ('Detect Poison and Disease', '/icons/spells/_mono/D.svg', '{"name":"Detect Poison and Disease","level":1,"school":"Divination","castingTime":"Action or Ritual","range":"Self","components":"V, S, M (a yew leaf)","duration":"Concentration, up to 10 minutes","classes":["Cleric","Druid","Paladin","Ranger"],"concentration":true}'),
    ('Divine Smite', '/icons/spells/_mono/D.svg', '{"name":"Divine Smite","level":1,"school":"Evocation","castingTime":"Bonus Action, which you take immediately after hitting a target with a Melee weapon or an Unarmed Strike","range":"Self","components":"V","duration":"Instantaneous","classes":["Paladin"],"damageType":"radiant"}'),
    ('Identify', '/icons/spells/_mono/I.svg', '{"name":"Identify","level":1,"school":"Divination","castingTime":"1 minute or Ritual","range":"Touch","components":"V, S, M (a pearl worth 100+ GP)","duration":"Instantaneous","classes":["Bard","Wizard"]}'),
    ('Illusory Script', '/icons/spells/_mono/I.svg', '{"name":"Illusory Script","level":1,"school":"Illusion","castingTime":"1 minute or Ritual","range":"Touch","components":"S, M (ink worth 10+ GP, which the spell consumes)","duration":"10 days","classes":["Bard","Warlock","Wizard"]}'),
    ('Jump', '/icons/spells/_mono/J.svg', '{"name":"Jump","level":1,"school":"Transmutation","castingTime":"Bonus Action","range":"Touch","components":"V, S, M (a grasshopper’s hind leg)","duration":"1 minute","classes":["Druid","Ranger","Sorcerer","Wizard"]}'),
    ('Purify Food and Drink', '/icons/spells/_mono/P.svg', '{"name":"Purify Food and Drink","level":1,"school":"Transmutation","castingTime":"Action or Ritual","range":"10 feet","components":"V, S","duration":"Instantaneous","classes":["Cleric","Druid","Paladin"]}'),
    ('Shield of Faith', '/icons/spells/_mono/S.svg', '{"name":"Shield of Faith","level":1,"school":"Abjuration","castingTime":"Bonus Action","range":"60 feet","components":"V, S, M (a prayer scroll)","duration":"Concentration, up to 10 minutes","classes":["Cleric","Paladin"],"concentration":true}'),
    ('Silent Image', '/icons/spells/_mono/S.svg', '{"name":"Silent Image","level":1,"school":"Illusion","castingTime":"Action","range":"60 feet","components":"V, S, M (a bit of fleece)","duration":"Concentration, up to 10 minutes","classes":["Bard","Sorcerer","Wizard"],"concentration":true}'),
    ('Tenser’s Floating Disk', '/icons/spells/_mono/T.svg', '{"name":"Tenser’s Floating Disk","level":1,"school":"Conjuration","castingTime":"Action","range":"30 feet","components":"V, S, M (a drop of mercury)","duration":"1 Hour","classes":["Wizard"]}'),
    ('Unseen Servant', '/icons/spells/_mono/U.svg', '{"name":"Unseen Servant","level":1,"school":"Conjuration","castingTime":"Action or Ritual","range":"60 feet","components":"V, S, M (a bit of string and of wood)","duration":"1 hour","classes":["Bard","Warlock","Wizard"]}'),
    ('Alter Self', '/icons/spells/_mono/A.svg', '{"name":"Alter Self","level":2,"school":"Transmutation","castingTime":"Action","range":"Self","components":"V, S","duration":"Concentration, up to 1 hour","classes":["Sorcerer","Wizard"],"concentration":true}'),
    ('Animal Messenger', '/icons/spells/_mono/A.svg', '{"name":"Animal Messenger","level":2,"school":"Enchantment","castingTime":"Action or Ritual","range":"30 feet","components":"V, S, M (a morsel of food)","duration":"24 hours","classes":["Bard","Druid","Ranger"]}'),
    ('Augury', '/icons/spells/_mono/A.svg', '{"name":"Augury","level":2,"school":"Divination","castingTime":"1 minute or Ritual","range":"Self","components":"V, S, M (specially marked sticks, bones, cards, or other divinatory tokens worth 25+ GP)","duration":"Instantaneous","classes":["Cleric","Druid","Wizard"]}'),
    ('Continual Flame', '/icons/spells/_mono/C.svg', '{"name":"Continual Flame","level":2,"school":"Evocation","castingTime":"Action","range":"Touch","components":"V, S, M (ruby dust worth 50+ GP, which the spell consumes)","duration":"Until dispelled","classes":["Cleric","Druid","Wizard"]}'),
    ('Dragon’s Breath', '/icons/spells/_mono/D.svg', '{"name":"Dragon’s Breath","level":2,"school":"Transmutation","castingTime":"Bonus Action","range":"Touch","components":"V, S, M (a hot pepper)","duration":"Concentration, up to 1 minute","classes":["Sorcerer","Wizard"],"concentration":true,"damageType":"varies","areaShape":"cone","areaSize":15}'),
    ('Find Steed', '/icons/spells/_mono/F.svg', '{"name":"Find Steed","level":2,"school":"Conjuration","castingTime":"Action","range":"30 feet","components":"V, S","duration":"Instantaneous","classes":["Paladin"]}'),
    ('Find Traps', '/icons/spells/_mono/F.svg', '{"name":"Find Traps","level":2,"school":"Divination","castingTime":"Action","range":"120 feet","components":"V, S","duration":"Instantaneous","classes":["Cleric","Druid","Ranger"]}'),
    ('Gentle Repose', '/icons/spells/_mono/G.svg', '{"name":"Gentle Repose","level":2,"school":"Necromancy","castingTime":"Action or Ritual","range":"Touch","components":"V, S, M (2 Copper Pieces, which the spell consumes)","duration":"10 days","classes":["Cleric","Paladin","Wizard"]}'),
    ('Levitate', '/icons/spells/_mono/L.svg', '{"name":"Levitate","level":2,"school":"Transmutation","castingTime":"Action","range":"60 feet","components":"V, S, M (a metal spring)","duration":"Concentration, up to 10 minutes","classes":["Sorcerer","Wizard"],"concentration":true}'),
    ('Locate Animals or Plants', '/icons/spells/_mono/L.svg', '{"name":"Locate Animals or Plants","level":2,"school":"Divination","castingTime":"Action or Ritual","range":"Self","components":"V, S, M (fur from a bloodhound)","duration":"Instantaneous","classes":["Bard","Druid","Ranger"]}'),
    ('Locate Object', '/icons/spells/_mono/L.svg', '{"name":"Locate Object","level":2,"school":"Divination","castingTime":"Action","range":"Self","components":"V, S, M (a forked twig)","duration":"Concentration, up to 10 minutes","classes":["Bard","Cleric","Druid","Paladin","Ranger","Wizard"],"concentration":true}'),
    ('Magic Mouth', '/icons/spells/_mono/M.svg', '{"name":"Magic Mouth","level":2,"school":"Illusion","castingTime":"1 minute or Ritual","range":"30 feet","components":"V, S, M (jade dust worth 10+ GP, which the spell consumes)","duration":"Until dispelled","classes":["Bard","Wizard"]}'),
    ('Nystul’s Magic Aura', '/icons/spells/_mono/N.svg', '{"name":"Nystul’s Magic Aura","level":2,"school":"Illusion","castingTime":"Action","range":"Touch","components":"V, S, M (a small square of silk)","duration":"24 Hours","classes":["Wizard"]}'),
    ('Rope Trick', '/icons/spells/_mono/R.svg', '{"name":"Rope Trick","level":2,"school":"Transmutation","castingTime":"Action","range":"Touch","components":"V, S, M (a segment of rope)","duration":"1 hour","classes":["Wizard"]}'),
    ('Shining Smite', '/icons/spells/_mono/S.svg', '{"name":"Shining Smite","level":2,"school":"Transmutation","castingTime":"Bonus Action","range":"Self","components":"V","duration":"1 Minute","classes":["Paladin"],"damageType":"radiant"}'),
    ('Spider Climb', '/icons/spells/_mono/S.svg', '{"name":"Spider Climb","level":2,"school":"Transmutation","castingTime":"Action","range":"Touch","components":"V, S, M (a drop of bitumen and a spider)","duration":"Concentration, up to 1 hour","classes":["Sorcerer","Warlock","Wizard"],"concentration":true}'),
    ('Suggestion', '/icons/spells/_mono/S.svg', '{"name":"Suggestion","level":2,"school":"Enchantment","castingTime":"Action","range":"30 feet","components":"V, M (a drop of honey)","duration":"Concentration, up to 8 hours","classes":["Bard","Sorcerer","Warlock","Wizard"],"concentration":true}'),
    ('Zone of Truth', '/icons/spells/_mono/Z.svg', '{"name":"Zone of Truth","level":2,"school":"Enchantment","castingTime":"Action","range":"60 feet","components":"V, S","duration":"10 minutes","classes":["Bard","Cleric","Paladin"]}'),
    ('Clairvoyance', '/icons/spells/_mono/C.svg', '{"name":"Clairvoyance","level":3,"school":"Divination","castingTime":"10 minutes","range":"1 mile","components":"V, S, M (a focus worth 100+ GP, either a jeweled horn for hearing or a glass eye for seeing)","duration":"Concentration, up to 10 minutes","classes":["Bard","Cleric","Sorcerer","Wizard"],"concentration":true}'),
    ('Conjure Animals', '/icons/spells/_mono/C.svg', '{"name":"Conjure Animals","level":3,"school":"Conjuration","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Concentration, up to 10 minutes","classes":["Druid","Ranger"],"concentration":true}'),
    ('Create Food and Water', '/icons/spells/_mono/C.svg', '{"name":"Create Food and Water","level":3,"school":"Conjuration","castingTime":"Action","range":"30 feet","components":"V, S","duration":"Instantaneous","classes":["Cleric","Paladin"]}'),
    ('Dispel Magic', '/icons/spells/_mono/D.svg', '{"name":"Dispel Magic","level":3,"school":"Abjuration","castingTime":"Action","range":"120 feet","components":"V, S","duration":"Instantaneous","classes":["Bard","Cleric","Druid","Paladin","Ranger","Sorcerer","Warlock","Wizard"]}'),
    ('Fly', '/icons/spells/_mono/F.svg', '{"name":"Fly","level":3,"school":"Transmutation","castingTime":"Action","range":"Touch","components":"V, S, M (a feather)","duration":"Concentration, up to 10 minutes","classes":["Sorcerer","Warlock","Wizard"],"concentration":true}'),
    ('Leomund’s Tiny Hut', '/icons/spells/_mono/L.svg', '{"name":"Leomund’s Tiny Hut","level":3,"school":"Evocation","castingTime":"1 Minute","range":"Self (10 ft. Sphere)","components":"V, S, M (a crystal bead)","duration":"8 Hours","classes":["Bard","Cleric","Wizard"]}'),
    ('Magic Circle', '/icons/spells/_mono/M.svg', '{"name":"Magic Circle","level":3,"school":"Abjuration","castingTime":"1 minute","range":"10 feet","components":"V, S, M (salt and powdered silver worth 100+ GP, which the spell consumes)","duration":"1 hour","classes":["Cleric","Paladin","Warlock","Wizard"]}'),
    ('Major Image', '/icons/spells/_mono/M.svg', '{"name":"Major Image","level":3,"school":"Illusion","castingTime":"Action","range":"120 feet","components":"V, S, M (a bit of fleece)","duration":"Concentration, up to 10 minutes","classes":["Bard","Sorcerer","Warlock","Wizard"],"concentration":true}'),
    ('Meld into Stone', '/icons/spells/_mono/M.svg', '{"name":"Meld into Stone","level":3,"school":"Transmutation","castingTime":"Action or Ritual","range":"Touch","components":"V, S","duration":"8 hours","classes":["Cleric","Druid","Ranger"]}'),
    ('Nondetection', '/icons/spells/_mono/N.svg', '{"name":"Nondetection","level":3,"school":"Abjuration","castingTime":"Action","range":"Touch","components":"V, S, M (a pinch of diamond dust worth 25+ GP, which the spell consumes)","duration":"8 hours","classes":["Bard","Ranger","Wizard"]}'),
    ('Phantom Steed', '/icons/spells/_mono/P.svg', '{"name":"Phantom Steed","level":3,"school":"Illusion","castingTime":"1 minute or Ritual","range":"30 feet","components":"V, S","duration":"1 hour","classes":["Wizard"]}'),
    ('Sending', '/icons/spells/_mono/S.svg', '{"name":"Sending","level":3,"school":"Divination","castingTime":"Action","range":"Unlimited","components":"V, S, M (a copper wire)","duration":"Instantaneous","classes":["Bard","Cleric","Wizard"]}'),
    ('Speak with Plants', '/icons/spells/_mono/S.svg', '{"name":"Speak with Plants","level":3,"school":"Transmutation","castingTime":"Action","range":"Self","components":"V, S","duration":"10 minutes","classes":["Bard","Druid","Ranger"]}'),
    ('Tongues', '/icons/spells/_mono/T.svg', '{"name":"Tongues","level":3,"school":"Divination","castingTime":"Action","range":"Touch","components":"V, M (a miniature ziggurat)","duration":"1 hour","classes":["Bard","Cleric","Sorcerer","Warlock","Wizard"]}'),
    ('Water Breathing', '/icons/spells/_mono/W.svg', '{"name":"Water Breathing","level":3,"school":"Transmutation","castingTime":"Action or Ritual","range":"30 feet","components":"V, S, M (a short reed)","duration":"24 hours","classes":["Druid","Ranger","Sorcerer","Wizard"]}'),
    ('Water Walk', '/icons/spells/_mono/W.svg', '{"name":"Water Walk","level":3,"school":"Transmutation","castingTime":"Action or Ritual","range":"30 feet","components":"V, S, M (a piece of cork)","duration":"1 hour","classes":["Cleric","Druid","Ranger","Sorcerer"]}'),
    ('Wind Wall', '/icons/spells/_mono/W.svg', '{"name":"Wind Wall","level":3,"school":"Evocation","castingTime":"Action","range":"120 feet","components":"V, S, M (a fan and a feather)","duration":"Concentration, up to 1 minute","classes":["Druid","Ranger"],"concentration":true,"areaShape":"line","areaSize":50}'),
    ('Arcane Eye', '/icons/spells/_mono/A.svg', '{"name":"Arcane Eye","level":4,"school":"Divination","castingTime":"Action","range":"30 feet","components":"V, S, M (a bit of bat fur)","duration":"Concentration, up to 1 hour","classes":["Wizard"],"concentration":true}'),
    ('Aura of Life', '/icons/spells/_mono/A.svg', '{"name":"Aura of Life","level":4,"school":"Abjuration","castingTime":"Action","range":"Self","components":"V","duration":"Concentration, up to 10 minutes","classes":["Cleric","Paladin"],"concentration":true}'),
    ('Charm Monster', '/icons/spells/_mono/C.svg', '{"name":"Charm Monster","level":4,"school":"Enchantment","castingTime":"Action","range":"30 feet","components":"V, S","duration":"1 hour","classes":["Bard","Druid","Sorcerer","Warlock","Wizard"]}'),
    ('Compulsion', '/icons/spells/_mono/C.svg', '{"name":"Compulsion","level":4,"school":"Enchantment","castingTime":"Action","range":"30 feet","components":"V, S","duration":"Concentration, up to 1 minute","classes":["Bard"],"concentration":true}'),
    ('Control Water', '/icons/spells/_mono/C.svg', '{"name":"Control Water","level":4,"school":"Transmutation","castingTime":"Action","range":"300 feet","components":"V, S, M (a mixture of water and dust)","duration":"Concentration, up to 10 minutes","classes":["Cleric","Druid","Wizard"],"concentration":true}'),
    ('Divination', '/icons/spells/_mono/D.svg', '{"name":"Divination","level":4,"school":"Divination","castingTime":"Action or Ritual","range":"Self","components":"V, S, M (incense worth 25+ GP, which the spell consumes)","duration":"Instantaneous","classes":["Cleric","Druid","Wizard"]}'),
    ('Fabricate', '/icons/spells/_mono/F.svg', '{"name":"Fabricate","level":4,"school":"Transmutation","castingTime":"10 minutes","range":"120 feet","components":"V, S","duration":"Instantaneous","classes":["Wizard"]}'),
    ('Giant Insect', '/icons/spells/_mono/G.svg', '{"name":"Giant Insect","level":4,"school":"Conjuration","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Concentration, up to 10 minutes","classes":["Druid"],"concentration":true}'),
    ('Hallucinatory Terrain', '/icons/spells/_mono/H.svg', '{"name":"Hallucinatory Terrain","level":4,"school":"Illusion","castingTime":"10 minutes","range":"300 feet","components":"V, S, M (a mushroom)","duration":"24 hours","classes":["Bard","Druid","Warlock","Wizard"]}'),
    ('Leomund’s Secret Chest', '/icons/spells/_mono/L.svg', '{"name":"Leomund’s Secret Chest","level":4,"school":"Conjuration","castingTime":"Action","range":"Touch","components":null,"duration":null,"classes":["Cleric","Wizard"]}'),
    ('Locate Creature', '/icons/spells/_mono/L.svg', '{"name":"Locate Creature","level":4,"school":"Divination","castingTime":"Action","range":"Self","components":"V, S, M (fur from a bloodhound)","duration":"Concentration, up to 1 hour","classes":["Bard","Cleric","Druid","Paladin","Ranger","Wizard"],"concentration":true}'),
    ('Mordenkainen’s Faithful Hound', '/icons/spells/_mono/M.svg', '{"name":"Mordenkainen’s Faithful Hound","level":4,"school":"Conjuration","castingTime":"Action","range":"30 feet","components":"V, S, M (a silver whistle)","duration":"8 Hours","classes":["Wizard"]}'),
    ('Mordenkainen’s Private Sanctum', '/icons/spells/_mono/M.svg', '{"name":"Mordenkainen’s Private Sanctum","level":4,"school":"Abjuration","castingTime":"10 Minutes","range":"120 feet (Square)","components":"V, S, M (a thin sheet of lead)","duration":"24 Hours","classes":["Wizard"]}'),
    ('Stone Shape', '/icons/spells/_mono/S.svg', '{"name":"Stone Shape","level":4,"school":"Transmutation","castingTime":"Action","range":"Touch","components":"V, S, M (soft clay)","duration":"Instantaneous","classes":["Cleric","Druid","Wizard"]}'),
    ('Vitriolic Sphere', '/icons/spells/_mono/V.svg', '{"name":"Vitriolic Sphere","level":4,"school":"Evocation","castingTime":"Action","range":"150 feet (20 ft. Sphere)","components":"V, S, M (a drop of bile)","duration":"Instantaneous","classes":["Sorcerer","Wizard"],"damageType":"acid","areaShape":"sphere","areaSize":20}'),
    ('Animate Objects', '/icons/spells/_mono/A.svg', '{"name":"Animate Objects","level":5,"school":"Transmutation","castingTime":"Action","range":"120 feet","components":"V, S","duration":"Concentration, up to 1 minute","classes":["Bard","Sorcerer","Wizard"],"concentration":true}'),
    ('Antilife Shell', '/icons/spells/_mono/A.svg', '{"name":"Antilife Shell","level":5,"school":"Abjuration","castingTime":"Action","range":"Self","components":"V, S","duration":"Concentration, up to 1 hour","classes":["Druid"],"concentration":true}'),
    ('Awaken', '/icons/spells/_mono/A.svg', '{"name":"Awaken","level":5,"school":"Transmutation","castingTime":"8 hours","range":"Touch","components":"V, S, M (an agate worth 1,000+ GP, which the spell consumes)","duration":"Instantaneous","classes":["Bard","Druid"]}'),
    ('Bigby’s Hand', '/icons/spells/_mono/B.svg', '{"name":"Bigby’s Hand","level":5,"school":"Evocation","castingTime":"Action","range":"120 feet","components":"V, S, M (an eggshell and a glove)","duration":"1 Minute","classes":["Sorcerer","Warlock","Wizard"]}'),
    ('Commune', '/icons/spells/_mono/C.svg', '{"name":"Commune","level":5,"school":"Divination","castingTime":"1 minute or Ritual","range":"Self","components":"V, S, M (incense)","duration":"1 minute","classes":["Cleric"]}'),
    ('Commune with Nature', '/icons/spells/_mono/C.svg', '{"name":"Commune with Nature","level":5,"school":"Divination","castingTime":"1 minute or Ritual","range":"Self","components":"V, S","duration":"Instantaneous","classes":["Druid","Ranger"]}'),
    ('Contact Other Plane', '/icons/spells/_mono/C.svg', '{"name":"Contact Other Plane","level":5,"school":"Divination","castingTime":"1 minute or Ritual","range":"Self","components":"V","duration":"1 minute","classes":["Warlock","Wizard"]}'),
    ('Creation', '/icons/spells/_mono/C.svg', '{"name":"Creation","level":5,"school":"Illusion","castingTime":"1 minute","range":"30 feet","components":"V, S, M (a paintbrush)","duration":"Special","classes":["Sorcerer","Wizard"]}'),
    ('Dream', '/icons/spells/_mono/D.svg', '{"name":"Dream","level":5,"school":"Illusion","castingTime":"1 minute","range":"Special","components":"V, S, M (a handful of sand)","duration":"8 hours","classes":["Bard","Warlock","Wizard"]}'),
    ('Geas', '/icons/spells/_mono/G.svg', '{"name":"Geas","level":5,"school":"Enchantment","castingTime":"1 minute","range":"60 feet","components":"V","duration":"30 days","classes":["Bard","Cleric","Druid","Paladin","Wizard"]}'),
    ('Hallow', '/icons/spells/_mono/H.svg', '{"name":"Hallow","level":5,"school":"Abjuration","castingTime":"24 hours","range":"Touch","components":"V, S, M (incense worth 1,000+ GP, which the spell consumes)","duration":"Until dispelled","classes":["Cleric"]}'),
    ('Legend Lore', '/icons/spells/_mono/L.svg', '{"name":"Legend Lore","level":5,"school":"Divination","castingTime":"10 minutes","range":"Self","components":"V, S, M (incense worth 250+ GP, which the spell consumes, and four ivory strips worth 50+ GP each)","duration":"Instantaneous","classes":["Bard","Cleric","Wizard"]}'),
    ('Mislead', '/icons/spells/_mono/M.svg', '{"name":"Mislead","level":5,"school":"Illusion","castingTime":"Action","range":"Self","components":"S","duration":"Concentration, up to 1 hour","classes":["Bard","Warlock","Wizard"],"concentration":true}'),
    ('Modify Memory', '/icons/spells/_mono/M.svg', '{"name":"Modify Memory","level":5,"school":"Enchantment","castingTime":"Action","range":"30 feet","components":"V, S","duration":"Concentration, up to 1 minute","classes":["Bard","Wizard"],"concentration":true}'),
    ('Passwall', '/icons/spells/_mono/P.svg', '{"name":"Passwall","level":5,"school":"Transmutation","castingTime":"Action","range":"30 feet","components":"V, S, M (a pinch of sesame seeds)","duration":"1 hour","classes":["Wizard"]}'),
    ('Raise Dead', '/icons/spells/_mono/R.svg', '{"name":"Raise Dead","level":5,"school":"Necromancy","castingTime":"1 hour","range":"Touch","components":"V, S, M (a diamond worth 500+ GP, which the spell consumes)","duration":"Instantaneous","classes":["Bard","Cleric","Paladin"]}'),
    ('Rary’s Telepathic Bond', '/icons/spells/_mono/R.svg', '{"name":"Rary’s Telepathic Bond","level":5,"school":"Divination","castingTime":"Action","range":"30 feet","components":"V, S, M (two eggs)","duration":"1 Hour","classes":["Bard","Cleric","Paladin","Sorcerer","Wizard"]}'),
    ('Reincarnate', '/icons/spells/_mono/R.svg', '{"name":"Reincarnate","level":5,"school":"Necromancy","castingTime":"1 hour","range":"Touch","components":"V, S, M (rare oils worth 1,000+ GP, which the spell consumes)","duration":"Instantaneous","classes":["Druid"]}'),
    ('Scrying', '/icons/spells/_mono/S.svg', '{"name":"Scrying","level":5,"school":"Divination","castingTime":"10 minutes","range":"Self","components":"V, S, M (a focus worth 1,000+ GP, such as a crystal ball, mirror, or water-filled font)","duration":"Concentration, up to 10 minutes","classes":["Bard","Cleric","Druid","Warlock","Wizard"],"concentration":true}'),
    ('Summon Dragon', '/icons/spells/_mono/S.svg', '{"name":"Summon Dragon","level":5,"school":"Conjuration","castingTime":"Action","range":"60 feet","components":"V, S, M (an object with the image of a dragon engraved on it worth 500+ GP)","duration":"Concentration, up to 1 hour","classes":["Wizard"],"concentration":true}'),
    ('Teleportation Circle', '/icons/spells/_mono/T.svg', '{"name":"Teleportation Circle","level":5,"school":"Conjuration","castingTime":"1 minute","range":"10 feet","components":"V, M (rare inks worth 50+ GP, which the spell consumes)","duration":"1 round","classes":["Bard","Sorcerer","Warlock","Wizard"]}'),
    ('Tree Stride', '/icons/spells/_mono/T.svg', '{"name":"Tree Stride","level":5,"school":"Conjuration","castingTime":"Action","range":"Self","components":"V, S","duration":"Concentration, up to 1 minute","classes":["Druid","Ranger"],"concentration":true}'),
    ('Wall of Force', '/icons/spells/_mono/W.svg', '{"name":"Wall of Force","level":5,"school":"Evocation","castingTime":"Action","range":"120 feet","components":"V, S, M (a shard of glass)","duration":"Concentration, up to 10 minutes","classes":["Wizard"],"concentration":true,"areaShape":"line","areaSize":30}'),
    ('Conjure Fey', '/icons/spells/_mono/C.svg', '{"name":"Conjure Fey","level":6,"school":"Conjuration","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Concentration, up to 10 minutes","classes":["Druid"],"concentration":true}'),
    ('Contingency', '/icons/spells/_mono/C.svg', '{"name":"Contingency","level":6,"school":"Abjuration","castingTime":"10 minutes","range":"Self","components":"V, S, M (a gem-encrusted statuette of yourself worth 1,500+ GP)","duration":"10 days","classes":["Wizard"]}'),
    ('Drawmij’s Instant Summons', '/icons/spells/_mono/D.svg', '{"name":"Drawmij’s Instant Summons","level":6,"school":"Conjuration","castingTime":"Action","range":"Touch","components":"V, S, M (a sapphire worth 1,000+ GP)","duration":"Until Dispelled","classes":["Wizard"]}'),
    ('Find the Path', '/icons/spells/_mono/F.svg', '{"name":"Find the Path","level":6,"school":"Divination","castingTime":"1 minute","range":"Self","components":"V, S, M (a set of divination tools—such as cards or runes—worth 100+ GP)","duration":"Concentration, up to 1 day","classes":["Bard","Cleric","Druid"],"concentration":true}'),
    ('Forbiddance', '/icons/spells/_mono/F.svg', '{"name":"Forbiddance","level":6,"school":"Abjuration","castingTime":"10 minutes or Ritual","range":"Touch","components":"V, S, M (ruby dust worth 1,000+ GP)","duration":"1 day","classes":["Cleric"]}'),
    ('Guards and Wards', '/icons/spells/_mono/G.svg', '{"name":"Guards and Wards","level":6,"school":"Abjuration","castingTime":"1 hour","range":"Touch","components":"V, S, M (a silver rod worth 10+ GP)","duration":"24 hours","classes":["Bard","Wizard"]}'),
    ('Magic Jar', '/icons/spells/_mono/M.svg', '{"name":"Magic Jar","level":6,"school":"Necromancy","castingTime":"1 minute","range":"Self","components":"V, S, M (a gem, crystal, or reliquary worth 500+ GP)","duration":"Until dispelled","classes":["Wizard"]}'),
    ('Mass Suggestion', '/icons/spells/_mono/M.svg', '{"name":"Mass Suggestion","level":6,"school":"Enchantment","castingTime":"Action","range":"60 feet","components":"V, M (a snake’s tongue)","duration":"24 hours","classes":["Bard","Sorcerer","Wizard"]}'),
    ('Move Earth', '/icons/spells/_mono/M.svg', '{"name":"Move Earth","level":6,"school":"Transmutation","castingTime":"Action","range":"120 feet","components":"V, S, M (a miniature shovel)","duration":"Concentration, up to 2 hours","classes":["Druid","Sorcerer","Wizard"],"concentration":true}'),
    ('Programmed Illusion', '/icons/spells/_mono/P.svg', '{"name":"Programmed Illusion","level":6,"school":"Illusion","castingTime":"Action","range":"120 feet","components":"V, S, M (jade dust worth 25+ GP)","duration":"Until dispelled","classes":["Bard","Wizard"]}'),
    ('Transport via Plants', '/icons/spells/_mono/T.svg', '{"name":"Transport via Plants","level":6,"school":"Conjuration","castingTime":"Action","range":"10 feet","components":"V, S","duration":"1 minute","classes":["Druid"]}'),
    ('True Seeing', '/icons/spells/_mono/T.svg', '{"name":"True Seeing","level":6,"school":"Divination","castingTime":"Action","range":"Touch","components":"V, S, M (mushroom powder worth 25+ GP, which the spell consumes)","duration":"1 hour","classes":["Bard","Cleric","Sorcerer","Warlock","Wizard"]}'),
    ('Word of Recall', '/icons/spells/_mono/W.svg', '{"name":"Word of Recall","level":6,"school":"Conjuration","castingTime":"Action","range":"5 feet","components":"V","duration":"Instantaneous","classes":["Cleric"]}'),
    ('Conjure Celestial', '/icons/spells/_mono/C.svg', '{"name":"Conjure Celestial","level":7,"school":"Conjuration","castingTime":"Action","range":"90 feet","components":"V, S","duration":"Concentration, up to 10 minutes","classes":["Cleric"],"concentration":true}'),
    ('Delayed Blast Fireball', '/icons/spells/_mono/D.svg', '{"name":"Delayed Blast Fireball","level":7,"school":"Evocation","castingTime":"Action","range":"150 feet","components":"V, S, M (a ball of bat guano and sulfur)","duration":"Concentration, up to 1 minute","classes":["Sorcerer","Wizard"],"concentration":true,"damageType":"fire","areaShape":"sphere","areaSize":20}'),
    ('Divine Word', '/icons/spells/_mono/D.svg', '{"name":"Divine Word","level":7,"school":"Evocation","castingTime":"Bonus Action","range":"30 feet","components":"V","duration":"Instantaneous","classes":["Cleric"]}'),
    ('Etherealness', '/icons/spells/_mono/E.svg', '{"name":"Etherealness","level":7,"school":"Conjuration","castingTime":"Action","range":"Self","components":"V, S","duration":"Up to 8 hours","classes":["Bard","Cleric","Sorcerer","Warlock","Wizard"]}'),
    ('Finger of Death', '/icons/spells/_mono/F.svg', '{"name":"Finger of Death","level":7,"school":"Necromancy","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Instantaneous","classes":["Sorcerer","Warlock","Wizard"],"damageType":"necrotic"}'),
    ('Fire Storm', '/icons/spells/_mono/F.svg', '{"name":"Fire Storm","level":7,"school":"Evocation","castingTime":"Action","range":"150 feet","components":"V, S","duration":"Instantaneous","classes":["Cleric","Druid","Sorcerer"],"damageType":"fire"}'),
    ('Forcecage', '/icons/spells/_mono/F.svg', '{"name":"Forcecage","level":7,"school":"Evocation","castingTime":"Action","range":"100 feet","components":"V, S, M (ruby dust worth 1,500+ GP, which the spell consumes)","duration":"Concentration, up to 1 hour","classes":["Bard","Warlock","Wizard"],"concentration":true}'),
    ('Mirage Arcane', '/icons/spells/_mono/M.svg', '{"name":"Mirage Arcane","level":7,"school":"Illusion","castingTime":"10 minutes","range":"Sight","components":"V, S","duration":"10 days","classes":["Bard","Druid","Wizard"]}'),
    ('Mordenkainen’s Magnificent Mansion', '/icons/spells/_mono/M.svg', '{"name":"Mordenkainen’s Magnificent Mansion","level":7,"school":"Conjuration","castingTime":"1 Minute","range":"300 feet","components":"V, S, M (a miniature door worth 15+ GP)","duration":"24 Hours","classes":["Bard","Wizard"]}'),
    ('Mordenkainen’s Sword', '/icons/spells/_mono/M.svg', '{"name":"Mordenkainen’s Sword","level":7,"school":"Evocation","castingTime":"Action","range":"90 feet","components":"V, S, M (a miniature sword worth 250+ GP)","duration":"1 Minute","classes":["Bard","Wizard"]}'),
    ('Plane Shift', '/icons/spells/_mono/P.svg', '{"name":"Plane Shift","level":7,"school":"Conjuration","castingTime":"Action","range":"Touch","components":"V, S, M (a forked, metal rod worth 250+ GP and attuned to a plane of existence)","duration":"Instantaneous","classes":["Cleric","Druid","Sorcerer","Warlock","Wizard"]}'),
    ('Prismatic Spray', '/icons/spells/_mono/P.svg', '{"name":"Prismatic Spray","level":7,"school":"Evocation","castingTime":"Action","range":"Self","components":"V, S","duration":"Instantaneous","classes":["Bard","Sorcerer","Wizard"],"damageType":"varies","areaShape":"cone","areaSize":60}'),
    ('Project Image', '/icons/spells/_mono/P.svg', '{"name":"Project Image","level":7,"school":"Illusion","castingTime":"Action","range":"500 miles","components":"V, S, M (a statuette of yourself worth 5+ GP)","duration":"Concentration, up to 1 day","classes":["Bard","Wizard"],"concentration":true}'),
    ('Regenerate', '/icons/spells/_mono/R.svg', '{"name":"Regenerate","level":7,"school":"Transmutation","castingTime":"1 minute","range":"Touch","components":"V, S, M (a prayer wheel)","duration":"1 hour","classes":["Bard","Cleric","Druid"]}'),
    ('Resurrection', '/icons/spells/_mono/R.svg', '{"name":"Resurrection","level":7,"school":"Necromancy","castingTime":"1 hour","range":"Touch","components":"V, S, M (a diamond worth 1,000+ GP, which the spell consumes)","duration":"Instantaneous","classes":["Bard","Cleric"]}'),
    ('Reverse Gravity', '/icons/spells/_mono/R.svg', '{"name":"Reverse Gravity","level":7,"school":"Transmutation","castingTime":"Action","range":"100 feet","components":"V, S, M (a lodestone and iron filings)","duration":"Concentration, up to 1 minute","classes":["Druid","Sorcerer","Wizard"],"concentration":true}'),
    ('Sequester', '/icons/spells/_mono/S.svg', '{"name":"Sequester","level":7,"school":"Transmutation","castingTime":"Action","range":"Touch","components":"V, S, M (gem dust worth 5,000+ GP, which the spell consumes)","duration":"Until dispelled","classes":["Wizard"]}'),
    ('Simulacrum', '/icons/spells/_mono/S.svg', '{"name":"Simulacrum","level":7,"school":"Illusion","castingTime":"12 hours","range":"Touch","components":"V, S, M (powdered ruby worth 1,500+ GP, which the spell consumes)","duration":"Until dispelled","classes":["Wizard"]}'),
    ('Symbol', '/icons/spells/_mono/S.svg', '{"name":"Symbol","level":7,"school":"Abjuration","castingTime":"1 minute","range":"Touch","components":"V, S, M (powdered diamond worth 1,000+ GP, which the spell consumes)","duration":"Until dispelled or triggered","classes":["Bard","Cleric","Druid","Wizard"]}'),
    ('Teleport', '/icons/spells/_mono/T.svg', '{"name":"Teleport","level":7,"school":"Conjuration","castingTime":"Action","range":"10 feet","components":"V","duration":"Instantaneous","classes":["Bard","Sorcerer","Wizard"]}'),
    ('Animal Shapes', '/icons/spells/_mono/A.svg', '{"name":"Animal Shapes","level":8,"school":"Transmutation","castingTime":"Action","range":"30 feet","components":"V, S","duration":"24 hours","classes":["Druid"]}'),
    ('Antimagic Field', '/icons/spells/_mono/A.svg', '{"name":"Antimagic Field","level":8,"school":"Abjuration","castingTime":"Action","range":"Self","components":"V, S, M (iron filings)","duration":"Concentration, up to 1 hour","classes":["Cleric","Wizard"],"concentration":true}'),
    ('Antipathy/Sympathy', '/icons/spells/_mono/A.svg', '{"name":"Antipathy/Sympathy","level":8,"school":"Enchantment","castingTime":"1 hour","range":"60 feet","components":"V, S, M (a mix of vinegar and honey)","duration":"10 days","classes":["Bard","Druid","Wizard"]}'),
    ('Befuddlement', '/icons/spells/_mono/B.svg', '{"name":"Befuddlement","level":8,"school":"Enchantment","castingTime":"Action","range":"150 feet","components":"V, S, M (a key ring with no keys)","duration":"Instantaneous","classes":["Bard","Druid","Warlock","Wizard"]}'),
    ('Clone', '/icons/spells/_mono/C.svg', '{"name":"Clone","level":8,"school":"Necromancy","castingTime":"1 hour","range":"Touch","components":null,"duration":null,"classes":["Wizard"]}'),
    ('Control Weather', '/icons/spells/_mono/C.svg', '{"name":"Control Weather","level":8,"school":"Transmutation","castingTime":"10 minutes","range":"Self","components":"V, S, M (burning incense)","duration":"Concentration, up to 8 hours","classes":["Cleric","Druid","Wizard"],"concentration":true}'),
    ('Demiplane', '/icons/spells/_mono/D.svg', '{"name":"Demiplane","level":8,"school":"Conjuration","castingTime":"Action","range":"60 feet","components":"S","duration":"1 hour","classes":["Sorcerer","Warlock","Wizard"]}'),
    ('Dominate Monster', '/icons/spells/_mono/D.svg', '{"name":"Dominate Monster","level":8,"school":"Enchantment","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Concentration, up to 1 hour","classes":["Bard","Sorcerer","Warlock","Wizard"],"concentration":true}'),
    ('Earthquake', '/icons/spells/_mono/E.svg', '{"name":"Earthquake","level":8,"school":"Transmutation","castingTime":"Action","range":"500 feet","components":"V, S, M (a fractured rock)","duration":"Concentration, up to 1 minute","classes":["Cleric","Druid","Sorcerer"],"concentration":true}'),
    ('Glibness', '/icons/spells/_mono/G.svg', '{"name":"Glibness","level":8,"school":"Enchantment","castingTime":"Action","range":"Self","components":"V","duration":"1 hour","classes":["Bard","Warlock"]}'),
    ('Holy Aura', '/icons/spells/_mono/H.svg', '{"name":"Holy Aura","level":8,"school":"Abjuration","castingTime":"Action","range":"Self","components":"V, S, M (a reliquary worth 1,000+ GP)","duration":"Concentration, up to 1 minute","classes":["Cleric"],"concentration":true}'),
    ('Incendiary Cloud', '/icons/spells/_mono/I.svg', '{"name":"Incendiary Cloud","level":8,"school":"Conjuration","castingTime":"Action","range":"150 feet","components":"V, S","duration":"Concentration, up to 1 minute","classes":["Druid","Sorcerer","Wizard"],"concentration":true,"damageType":"fire","areaShape":"sphere","areaSize":20}'),
    ('Maze', '/icons/spells/_mono/M.svg', '{"name":"Maze","level":8,"school":"Conjuration","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Concentration, up to 10 minutes","classes":["Wizard"],"concentration":true}'),
    ('Mind Blank', '/icons/spells/_mono/M.svg', '{"name":"Mind Blank","level":8,"school":"Abjuration","castingTime":"Action","range":"Touch","components":"V, S","duration":"24 hours","classes":["Bard","Wizard"]}'),
    ('Power Word Stun', '/icons/spells/_mono/P.svg', '{"name":"Power Word Stun","level":8,"school":"Enchantment","castingTime":"Action","range":"60 feet","components":"V","duration":"Instantaneous","classes":["Bard","Sorcerer","Warlock","Wizard"]}'),
    ('Sunburst', '/icons/spells/_mono/S.svg', '{"name":"Sunburst","level":8,"school":"Evocation","castingTime":"Action","range":"150 feet","components":"V, S, M (a piece of sunstone)","duration":"Instantaneous","classes":["Cleric","Druid","Sorcerer","Wizard"],"damageType":"radiant","areaShape":"sphere","areaSize":60}'),
    ('Tsunami', '/icons/spells/_mono/T.svg', '{"name":"Tsunami","level":8,"school":"Conjuration","castingTime":"1 Minute","range":"1 Mile","components":"V, S","duration":"6 Rounds","classes":["Druid"]}'),
    ('Astral Projection', '/icons/spells/_mono/A.svg', '{"name":"Astral Projection","level":9,"school":"Necromancy","castingTime":"1 hour","range":"10 feet","components":"V, S, M (for each of the spell’s targets, one jacinth worth 1,000+ GP and one silver bar worth 100+ GP, all of which the spell consumes)","duration":"Un","classes":["Cleric","Warlock","Wizard"]}'),
    ('Foresight', '/icons/spells/_mono/F.svg', '{"name":"Foresight","level":9,"school":"Divination","castingTime":"1 minute","range":"Touch","components":"V, S, M (a hummingbird feather)","duration":"8 hours","classes":["Bard","Druid","Warlock","Wizard"]}'),
    ('Gate', '/icons/spells/_mono/G.svg', '{"name":"Gate","level":9,"school":"Conjuration","castingTime":"Action","range":"60 feet","components":"V, S, M (a diamond worth 5,000+ GP)","duration":"Concentration, up to 1 minute","classes":["Cleric","Sorcerer","Warlock","Wizard"],"concentration":true}'),
    ('Imprisonment', '/icons/spells/_mono/I.svg', '{"name":"Imprisonment","level":9,"school":"Abjuration","castingTime":"1 minute","range":"30 feet","components":"V, S, M (a statuette of the target worth 5,000+ GP)","duration":"Until dispelled","classes":["Warlock","Wizard"]}'),
    ('Mass Heal', '/icons/spells/_mono/M.svg', '{"name":"Mass Heal","level":9,"school":"Abjuration","castingTime":"Action","range":"60 feet","components":"V, S","duration":"Instantaneous","classes":["Cleric"]}'),
    ('Meteor Swarm', '/icons/spells/_mono/M.svg', '{"name":"Meteor Swarm","level":9,"school":"Evocation","castingTime":"Action","range":"1 mile","components":"V, S","duration":"Instantaneous","classes":["Sorcerer","Wizard"],"damageType":"fire","areaShape":"sphere","areaSize":40}'),
    ('Power Word Heal', '/icons/spells/_mono/P.svg', '{"name":"Power Word Heal","level":9,"school":"Enchantment","castingTime":"Action","range":"60 feet","components":"V","duration":"Instantaneous","classes":["Bard","Cleric"]}'),
    ('Prismatic Wall', '/icons/spells/_mono/P.svg', '{"name":"Prismatic Wall","level":9,"school":"Abjuration","castingTime":"Action","range":"60 feet","components":"V, S","duration":"10 minutes","classes":["Bard","Wizard"],"areaShape":"line","areaSize":90}'),
    ('Shapechange', '/icons/spells/_mono/S.svg', '{"name":"Shapechange","level":9,"school":"Transmutation","castingTime":"Action","range":"Self","components":"V, S, M (a jade circlet worth 1,500+ GP)","duration":"Concentration, up to 1 hour","classes":["Druid","Wizard"],"concentration":true}'),
    ('Storm of Vengeance', '/icons/spells/_mono/S.svg', '{"name":"Storm of Vengeance","level":9,"school":"Conjuration","castingTime":"Action","range":"1 mile","components":"V, S","duration":"Concentration, up to 1 minute","classes":["Druid"],"concentration":true}'),
    ('Time Stop', '/icons/spells/_mono/T.svg', '{"name":"Time Stop","level":9,"school":"Transmutation","castingTime":"Action","range":"Self","components":"V","duration":"Instantaneous","classes":["Sorcerer","Wizard"]}'),
    ('True Polymorph', '/icons/spells/_mono/T.svg', '{"name":"True Polymorph","level":9,"school":"Transmutation","castingTime":"Action","range":"30 feet","components":"V, S, M (a drop of mercury, a dollop of gum arabic, and a wisp of smoke)","duration":"Concentration, up to 1 hour","classes":["Bard","Warlock","Wizard"],"concentration":true}'),
    ('True Resurrection', '/icons/spells/_mono/T.svg', '{"name":"True Resurrection","level":9,"school":"Necromancy","castingTime":"1 hour","range":"Touch","components":"V, S, M (diamonds worth 25,000+ GP, which the spell consumes)","duration":"Instantaneous","classes":["Cleric","Druid"]}'),
    ('Weird', '/icons/spells/_mono/W.svg', '{"name":"Weird","level":9,"school":"Illusion","castingTime":"Action","range":"120 feet","components":"V, S","duration":"Concentration, up to 1 minute","classes":["Warlock","Wizard"],"concentration":true}'),
    ('Wish', '/icons/spells/_mono/W.svg', '{"name":"Wish","level":9,"school":"Conjuration","castingTime":"Action","range":"Self","components":"V","duration":"Instantaneous","classes":["Sorcerer","Wizard"]}')
  ) as v(name, image_url, spell)
  where not exists (
    select 1 from public.token_assets t
    where t.owner_id = me and t.token_type = 'spell' and t.name = v.name
  );
end $$;
